// Fluent System Icons (MIT, Microsoft). Only the icons listed here are bundled.
import sidebar from '@fluentui/svg-icons/icons/panel_left_20_regular.svg?raw'
import zoomIn from '@fluentui/svg-icons/icons/zoom_in_20_regular.svg?raw'
import zoomOut from '@fluentui/svg-icons/icons/zoom_out_20_regular.svg?raw'
import rotateRight from '@fluentui/svg-icons/icons/arrow_rotate_clockwise_20_regular.svg?raw'
import rotateLeft from '@fluentui/svg-icons/icons/arrow_rotate_counterclockwise_20_regular.svg?raw'
import highlight from '@fluentui/svg-icons/icons/highlight_20_regular.svg?raw'
import search from '@fluentui/svg-icons/icons/search_20_regular.svg?raw'
import print from '@fluentui/svg-icons/icons/print_20_regular.svg?raw'
import share from '@fluentui/svg-icons/icons/share_20_regular.svg?raw'
import more from '@fluentui/svg-icons/icons/more_horizontal_20_regular.svg?raw'
import up from '@fluentui/svg-icons/icons/chevron_up_20_regular.svg?raw'
import down from '@fluentui/svg-icons/icons/chevron_down_20_regular.svg?raw'
import left from '@fluentui/svg-icons/icons/chevron_left_20_regular.svg?raw'
import right from '@fluentui/svg-icons/icons/chevron_right_20_regular.svg?raw'
import open from '@fluentui/svg-icons/icons/folder_open_20_regular.svg?raw'
import close from '@fluentui/svg-icons/icons/dismiss_20_regular.svg?raw'
import settings from '@fluentui/svg-icons/icons/settings_20_regular.svg?raw'
import grid from '@fluentui/svg-icons/icons/grid_20_regular.svg?raw'
import toc from '@fluentui/svg-icons/icons/text_bullet_list_tree_20_regular.svg?raw'
import bookmark from '@fluentui/svg-icons/icons/bookmark_20_regular.svg?raw'
import moon from '@fluentui/svg-icons/icons/weather_moon_20_regular.svg?raw'
import save from '@fluentui/svg-icons/icons/save_20_regular.svg?raw'
import trash from '@fluentui/svg-icons/icons/delete_20_regular.svg?raw'
import add from '@fluentui/svg-icons/icons/add_20_regular.svg?raw'
import addPage from '@fluentui/svg-icons/icons/document_add_20_regular.svg?raw'
import fullscreen from '@fluentui/svg-icons/icons/full_screen_maximize_20_regular.svg?raw'
import slideshow from '@fluentui/svg-icons/icons/slide_multiple_20_regular.svg?raw'
import fitPage from '@fluentui/svg-icons/icons/page_fit_20_regular.svg?raw'
import zoomFit from '@fluentui/svg-icons/icons/zoom_fit_20_regular.svg?raw'
import undo from '@fluentui/svg-icons/icons/arrow_undo_20_regular.svg?raw'
import redo from '@fluentui/svg-icons/icons/arrow_redo_20_regular.svg?raw'
import edit from '@fluentui/svg-icons/icons/edit_20_regular.svg?raw'
import check from '@fluentui/svg-icons/icons/checkmark_20_regular.svg?raw'
import copy from '@fluentui/svg-icons/icons/copy_20_regular.svg?raw'
import image from '@fluentui/svg-icons/icons/image_20_regular.svg?raw'
import cube from '@fluentui/svg-icons/icons/cube_20_regular.svg?raw'
import info from '@fluentui/svg-icons/icons/info_20_regular.svg?raw'
import newWindow from '@fluentui/svg-icons/icons/window_new_20_regular.svg?raw'
import document from '@fluentui/svg-icons/icons/document_20_regular.svg?raw'
import pen from '@fluentui/svg-icons/icons/pen_20_regular.svg?raw'
import markup from '@fluentui/svg-icons/icons/edit_20_regular.svg?raw'

export const ICONS = { sidebar, zoomIn, zoomOut, rotateRight, rotateLeft, highlight, search, print, share, more, up, down, left, right, open, close, settings, grid, toc, bookmark, moon, save, trash, add, addPage, fullscreen, slideshow, fitPage, zoomFit, undo, redo, edit, check, copy, image, cube, info, newWindow, document, pen, markup }
export type IconName = keyof typeof ICONS
